require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ReactNativeUiComponentsExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.  
  # use_flipper!({ "Flipper-DoubleConversion" => "1.1.7" }) # to fix build error 'duplicate symbol 'folly::detail::str_to_bool(folly::Range<char const*>*)' in:'
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end
