#!/usr/bin/env node

// hook that validates that a major change commit contains the mention 'BREAKING CHANGE'

const fs = require('fs');

const message = fs.readFileSync(process.argv[2], 'utf8').trim();

if (message.includes('chore(release)')) {
  process.exit(0);
}

const commitMsgSplitted = message.split('\n');
const commitSubject = commitMsgSplitted[0];

const majorCommitTypeRegex = /^major[(a-zA-Z.)]*:/g;
const majorCommitType = commitSubject.match(majorCommitTypeRegex);

if (!majorCommitType || majorCommitType.length === 0) {
  process.exit(0);
}

if (
  !message.includes('BREAKING CHANGE:') &&
  !message.includes('BREAKING CHANGES:')
) {
  console.log(
    "❌ Wrong commit format for a major change. Please mention 'BREAKING CHANGE:' at the beginning of the commit footer and explain the breaking change."
  );

  process.exit(1);
}

process.exit(0);
