#!/usr/bin/env node

// this script validates that a commit message that contains BREAKING CHANGE contains an exclamation mark (!) in
// its subject (just after the commit type(scope))

const fs = require('fs');

const message = fs.readFileSync(process.argv[2], 'utf8').trim();

if (!message.includes('BREAKING CHANGE')) {
  process.exit(0);
}

const commitMsgSplitted = message.split('\n');
const commitSubject = commitMsgSplitted[0];
const commitEmojiAndTypeRegex = /^:[A-Za-z]*: [A-Za-z()]*!:/g;
const commitEmojiAndType = commitSubject.match(commitEmojiAndTypeRegex);

if (!commitEmojiAndType || commitEmojiAndType.length === 0) {
  console.log(
    "❌ Wrong commit format for a BREAKING CHANGE. Please add an exclamation mark '!' just after your commit type(scope).\nFor example: :sparkles: feat(ui)!: new component"
  );

  process.exit(1);
}

process.exit(0);
