# This workflow is triggered when commits gets pushed to master branch
# It calls the reusable workflow lint-tests

name: Push to Master

concurrency:
  group: push-to-master # to run only one build of this type at a time

on:
  push:
    branches: 
      - master  
      

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile
      
      - name: Lint all codebase
        run: yarn lint

      - name: Run all tests
        run: yarn test
 

      - name: Release
        env:
          GITHUB_TOKEN: ${{secrets.CI_GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: yarn release
